/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lupipackage;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import java.util.logging.*;
import javax.swing.JComboBox;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author jahp0
 */
public class LupiDepreciacion extends javax.swing.JFrame {

 private static final Logger logger =Logger.getLogger(LupiDepreciacion.class.getName());
    /**
     * Creates new form LupiDepreciacion
     */
    public LupiDepreciacion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jNombreActivo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jValorActivo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jValorResidual = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jAnosVida = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jTipoActivo = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nombre del activo");

        jLabel2.setText("Valor del activo");

        jLabel3.setText("Valor residual");

        jLabel4.setText("Años de vida:");

        jButton1.setText("Calcular");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel5.setText("Tipo de Activo");

        jTipoActivo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Edificios", "Vehiculos", "Maquinaria", "Mobiliario", "Equipos de oficina" }));
        jTipoActivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTipoActivoActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jScrollPane1.setViewportView(jTable1);

        jScrollPane2.setViewportView(jScrollPane1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGap(45, 45, 45)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jNombreActivo)
                                    .addComponent(jValorActivo)
                                    .addComponent(jValorResidual, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                                    .addComponent(jAnosVida)
                                    .addComponent(jTipoActivo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(141, 141, 141)
                                .addComponent(jButton1)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jNombreActivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jValorActivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTipoActivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jValorResidual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jAnosVida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jAnosVida, jLabel1, jLabel2, jLabel3, jLabel4, jNombreActivo, jValorActivo, jValorResidual});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         double depreciacion;
                int valoractivo=0;
                int valorrescate=0;
                int vidautil=0;
                
        
        String msj="";
        //primero validamos
        if (jValorActivo.getText().equals(""))
        {
            msj="Debe digitar el valor del activo";
        }
        else if (jValorResidual.getText()=="") 
        {
            msj="Debe digitar el valor residual del activo";
        }
        else if (jAnosVida.getText()=="") {
            msj="Debe digitar los años de vida";
        }
        else 
        {
            if (!msj.equals("")) {
                JOptionPane.showMessageDialog(this, msj);
            }
            else 
            {
             vidautil=Integer.parseInt(jAnosVida.getText());
             valoractivo=Integer.parseInt(jValorActivo.getText());
             valorrescate=Integer.parseInt(jValorResidual.getText());
             depreciacion=this.depreciacion(valoractivo, valorrescate, vidautil);
             ArrayList<String> datos= new ArrayList();
             
             logger.info("Viendo los datos calculados");
             logger.info(Double.toString(depreciacion));
             for (int x=0;x < vidautil; x++)
             {
                 datos.add(Double.toString(depreciacion));
                  
             }
             logger.info(datos.toString());
             llenartabla(datos);
            }
            
            
        }
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTipoActivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTipoActivoActionPerformed
        // TODO add your handling code here:
        int selection = jTipoActivo.getSelectedIndex();
            switch (selection) {
                case 0:
                    jAnosVida.setText("20");
                    break;
                case 1:
                     jAnosVida.setText("5");
                    break;
                    case 2:
                     jAnosVida.setText("8");
                    break;
                    case 3:
                     jAnosVida.setText("2");
                    break;
                default:
                    jAnosVida.setText("1");
                    break;
            }
    }//GEN-LAST:event_jTipoActivoActionPerformed


    
    private void llenartabla(ArrayList<String> pdatos){
        logger.info("llenar tabla");
        String[] columnas = new String[21];
        columnas[0]="Activo";
        for (int x = 1; x <=20; x++){
            String incremento;
            incremento = Integer.toString(x);
            columnas[x]="Año ".concat(incremento);
        }
        jTable1.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        DefaultTableModel tableModel = new DefaultTableModel(columnas, 0);
        logger.info("viendo el tamaño del arreglo");
        logger.info(Integer.toString(pdatos.size()-1));
         int ano=0;
         Object[] data = new Object[21];
         data[0]=jNombreActivo.getText();
        for (String i: pdatos) {
            
            ano++;
            
             
            data[ano]=i;
         
         
         
          
        
        
        }
         tableModel.addRow(data);
        this.jTable1.setModel(tableModel);
        logger.info("Antes de repaint");
        this.jTable1.repaint();
         tableModel.fireTableDataChanged();
        logger.info("Despues del repaint");
    }   
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LupiDepreciacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LupiDepreciacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LupiDepreciacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LupiDepreciacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LupiDepreciacion().setVisible(true);
            }
        });
    }

    public double depreciacion(int valor, int valorrescate, int vidautil) {
        double deprec=0.0;
        deprec=(valor-valorrescate)/vidautil;
        return deprec;
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField jAnosVida;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jNombreActivo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JComboBox<String> jTipoActivo;
    private javax.swing.JTextField jValorActivo;
    private javax.swing.JTextField jValorResidual;
    // End of variables declaration//GEN-END:variables
}
