/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PackServer;

import PackCliente.Cliente;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.net.ServerSocket;
import java.net.Socket;
import java.util.logging.*;
/**
 *
 * @author Celeste
 */
public class Chat_Server extends javax.swing.JFrame implements Runnable{
    private static final Logger logger =Logger.getLogger(Chat_Server.class.getName());
    private ObjectInputStream entrada;
    private ServerSocket sSocket;
    private Socket cSocket;
    
    public Chat_Server() {
        logger.info("Método chat server");
        initComponents();
        Thread hiloServer= new Thread(this);
        hiloServer.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtServer = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtServer.setEditable(false);
        txtServer.setColumns(20);
        txtServer.setRows(5);
        jScrollPane1.setViewportView(txtServer);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Chat_Server.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Chat_Server.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Chat_Server.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Chat_Server.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               logger.info("Estoy en main");
                new Chat_Server().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtServer;
    // End of variables declaration//GEN-END:variables

    @Override
    public void run() {
        String nombre,ip,msj;
        try {
            sSocket= new ServerSocket(1306);
            logger.info("Abriendo al puerto 1306");
            Cliente recibido;
            while(true){
                cSocket=sSocket.accept();
                entrada=new ObjectInputStream(cSocket.getInputStream());
                recibido=(Cliente) entrada.readObject();
                nombre=recibido.getNombre();
                ip=recibido.getIp();
                msj=recibido.getMensaje();
                logger.info("Viendo la ip".concat(ip));
                logger.info("Viendo el nombre: ".concat(nombre));
                //txtServer.append("\n"+recibido.getNombre()+" : "+recibido.getMensaje()+"\n");
                txtServer.append("Cliente: "+nombre+ "   IP: "+ip+"\n"+"Mensaje: "+msj+"\n");
                Socket enviar= new Socket(ip,2020);
                ObjectOutputStream salida= new ObjectOutputStream(enviar.getOutputStream());
                salida.writeObject(recibido);
               cSocket.close();
            }
        } catch (IOException ex) {
            System.out.println(ex.getMessage());
        } catch (ClassNotFoundException ex) {
            System.out.println(ex.getMessage());
        }
    }
    
    private void close() throws IOException{
        logger.info("Se supone que estoy cerrando");
        entrada.close();
        cSocket.close();
        sSocket.close();
    }
}